include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_super_parameters: ignore
    avoid_print: ignore
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
