name: flutterx_starter_kit
description: "A comprehensive starter kit to accelerate Flutter application development with ready-to-use components following best practices."
version: 0.0.11
homepage: https://github.com/ramadhanhadiatmaa/flutterx_starter_kit
repository: https://github.com/ramadhanhadiatmaa/flutterx_starter_kit

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  test: ^1.25.0
  http_mock_adapter: ^0.6.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter: null
