name: flutterx_starter_kit
description: "A comprehensive starter kit that accelerates Flutter app
  development with ready-to-use components and best practices, especially for
  GetX state management."
version: 0.0.6
homepage: https://github.com/ramadhanhadiatmaa/flutterx_starter_kit
repository: https://github.com/ramadhanhadiatmaa/flutterx_starter_kit

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

executables:
  flutterx: flutterx

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  google_fonts: ^6.3.2
  http: ^1.5.0
  path: ^1.9.0
  recase: ^4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  test: ^1.25.0

flutter: null
